# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-12-13 16:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='character',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('charname', models.CharField(default='', help_text='Your Name', max_length=40)),
                ('hp', models.IntegerField(default=1, help_text='Hit Points')),
                ('ac', models.IntegerField(default=10, help_text='Armor Class')),
            ],
        ),
    ]
